# src/main/resources/application.yml
server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Configure redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

#Configure Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka