# src/main/resources/application.yml
server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service # dùng service name đăng ký với Eureka
          predicates:
            - Path=/api/users/**
# Do not need auth for auth endpoints anymore, handled in user-service itself by keycloak
#        - id: user-service-auth
#          uri: lb://user-service
#          predicates:
#            - Path=/api/auth/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka