# src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service # dùng service name đăng ký với Eureka
          predicates:
            - Path=/api/users/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka